### ISSUE TITLE
Speed Test

### ISSUE THREAD

**Issue by 78Alpha** [78Alpha/Auto1111-FORK#2]
Testing to see the maximum performance of the available cards and what settings are needed to hit those top speeds. Direct code alterations are not permitted. This is meant to test end user speed.

Commit: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8

Standards:

- V1-5-pruned-emaonly
- 512 x 512
- cfg 7
- Euler a
- Steps 20

Links will direct to peak performance settings
- [x] RTX 3070 [Single](https://github.com/78Alpha/Auto1111-FORK/issues/2#issuecomment-1458548521) | [Batch8](https://github.com/78Alpha/Auto1111-FORK/issues/2#issuecomment-1457350949)
- [x] RTX 3090 [Single](https://github.com/78Alpha/Auto1111-FORK/issues/2#issuecomment-1475351091) | [Batch8](https://github.com/78Alpha/Auto1111-FORK/issues/2#issuecomment-1475351968)
- [ ] RTX 2060
- [x] Tesla P40 [Single](https://github.com/78Alpha/Auto1111-FORK/issues/2#issuecomment-1459159559) | [Batch8](https://github.com/78Alpha/Auto1111-FORK/issues/2#issuecomment-1459143098)

**Comment by 78Alpha** [comment]
### RTX 3070

**Test 1**

_Command Line Arguments:_ N/A
_XFORMERS:_ False
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ Autocast
_Batch Size_: 1

Result:

9.16 it/s raw | 7.90 it/s load
9.16 it/s avg @ BS1

**Comment by 78Alpha** [comment]
### RTX 3070

**Test 2**

_Command Line Arguments:_ N/A
_XFORMERS:_ False
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ Autocast
_Batch Size_: 8

Result:

1.38 it/s raw | 1.20 it/s load
11.04 it/s avg @ BS8

**Comment by 78Alpha** [comment]
### RTX 3070

**Test 3**

_Command Line Arguments:_ N/A
_XFORMERS:_ False
_Torch:_ 1.13.1+cu117
_CuDNN:_ 8.8.0
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ Autocast
_Batch Size_: 8

Result:

1.4 it/s raw | 1.21 it/s load
11.2 it/s avg @ BS8

**Comment by 78Alpha** [comment]
### RTX 3070

**Test 4**

_Command Line Arguments:_ --opt-channelslast
_XFORMERS:_ False
_Torch:_ 1.13.1+cu117
_CuDNN:_ 8.8.0
_Triton:_ False
_Opt-channelslast:_ True
_Precision:_ Autocast
_Batch Size_: 8

Result:

1.36 it/s raw | 1.16 it/s load
10.88 it/s avg @ BS8

**Comment by 78Alpha** [comment]
### RTX 3070

**Test 5**

_Command Line Arguments:_ --opt-channelslast --xformers
_XFORMERS:_ 0.016rc425
_Torch:_ 1.13.1+cu117
_CuDNN:_ 8.8.0
_Triton:_ False
_Opt-channelslast:_ True
_Precision:_ Autocast
_Batch Size_: 8

Result:

1.77 it/s raw | 1.44 it/s load
14.16 it/s avg @ BS8

**Comment by 78Alpha** [comment]
### RTX 3070

**Test 6**

_Command Line Arguments:_ --xformers
_XFORMERS:_ 0.016rc425
_Torch:_ 1.13.1+cu117
_CuDNN:_ 8.8.0
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ Autocast
_Batch Size_: 8

Result:

1.8 it/s raw | 1.51 it/s load
14.4 it/s avg @ BS8

**Comment by 78Alpha** [comment]
### RTX 3070

**Test 7**

_Command Line Arguments:_  --xformers
_XFORMERS:_ 0.016rc425
_Torch:_ 1.13.1+cu117
_CuDNN:_ 8.8.0
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ Autocast
_Batch Size_: 1

Result:

10.64 it/s raw | 9.17 it/s load
10.64 it/s avg @ BS1

**Comment by 78Alpha** [comment]
### RTX 3070

**Test 7**

_Command Line Arguments:_  --xformers --opt-channelslast
_XFORMERS:_ 0.016rc425
_Torch:_ 1.13.1+cu117
_CuDNN:_ 8.8.0
_Triton:_ False
_Opt-channelslast:_ True
_Precision:_ Autocast
_Batch Size_: 1

Result:

11.4 it/s raw | 9.58 it/s load
11.4 it/s avg @ BS1

**Comment by 78Alpha** [comment]
### RTX 3070

**Test 8**

_Command Line Arguments:_  --xformers --opt-channelslast
_XFORMERS:_ 0.0.17+b89a493.d20230306
_Torch:_ 1.13.1+cu117
_CuDNN:_ 8.8.0
_Triton:_ False
_Opt-channelslast:_ True
_Precision:_ Autocast
_Batch Size_: 1

Result:

11.43 it/s raw | 9.55 it/s load
11.43 it/s avg @ BS1

**Comment by 78Alpha** [comment]
### RTX 3070

**Test 9**

_Command Line Arguments:_  --xformers --opt-channelslast
_XFORMERS:_ 0.0.17+b89a493.d20230306
_Torch:_ 1.13.1+cu117
_CuDNN:_ 8.8.0
_Triton:_ False
_Opt-channelslast:_ True
_Precision:_ Autocast
_Batch Size_: 8

Result:

1.76 it/s raw | 1.42 it/s load
14.08 it/s avg @ BS8

**Comment by 78Alpha** [comment]
### TESLA P40

**Test 1**

_Command Line Arguments:_ N/A
_XFORMERS:_ False
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ Autocast
_Batch Size_: 1

Result:

2.54 it/s raw | 2.38 it/s load
2.54 it/s avg @ BS1

**Comment by 78Alpha** [comment]
### TESLA P40

**Test 2**

_Command Line Arguments:_ N/A
_XFORMERS:_ False
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ Autocast
_Batch Size_: 8

Result:

1.83 s/it raw | 2.02 s/it load
4.37 it/s avg @ BS8

**Comment by 78Alpha** [comment]
### TESLA P40

**Test 3**

_Command Line Arguments:_ N/A
_XFORMERS:_ False
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ Autocast
_Batch Size_: 1

Other: Upcast Cross Attention to FP32

Result:

2.25 it/s raw | 2.12 it/s load
2.25 it/s avg @ BS1

**Comment by 78Alpha** [comment]
### TESLA P40

**Test 4**

_Command Line Arguments:_ N/A
_XFORMERS:_ False
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ Autocast
_Batch Size_: 6

Other: Upcast Cross Attention to FP32

Result:

1.73 s/it raw | 1.88 s/it load
3.46 it/s avg @ BS6

**Comment by 78Alpha** [comment]
### TESLA P40

**Test 5**

_Command Line Arguments:_ N/A
_XFORMERS:_ False
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ Autocast
_Batch Size_: 4

Other: Upcast Cross Attention to FP32

Result:

1.27 s/it raw | 1.36 s/it load
3.14 it/s avg @ BS4

**Comment by 78Alpha** [comment]
### TESLA P40

**Test 6**

_Command Line Arguments:_ --no-half --precision full --no-half-vae
_XFORMERS:_ False
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ FULL
_Batch Size_: 1

Result:

2.71 it/s raw | 2.54 it/s load
2.71 it/s avg @ BS1

**Comment by 78Alpha** [comment]
### TESLA P40

**Test 7**

_Command Line Arguments:_ --no-half --precision full --no-half-vae
_XFORMERS:_ False
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ FULL
_Batch Size_: 8

Result:

2.18 s/it raw | 2.38 s/it load
3.66 it/s avg @ BS8

**Comment by 78Alpha** [comment]
### TESLA P40

**Test 8**

_Command Line Arguments:_ --no-half --precision full --no-half-vae --opt-channelslast
_XFORMERS:_ False
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ True
_Precision:_ FULL
_Batch Size_: 1

Result:

2.44 it/s raw | 2.24 it/s load
2.44 it/s avg @ BS1

**Comment by 78Alpha** [comment]
### TESLA P40

**Test 9**

_Command Line Arguments:_ --no-half --precision full --no-half-vae --opt-channelslast
_XFORMERS:_ False
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ True
_Precision:_ FULL
_Batch Size_: 8

Result:

2.69 s/it raw | 2.97 s/it load
2.97 it/s avg @ BS8

**Comment by 78Alpha** [comment]
### TESLA P40

**Test 10**

_Command Line Arguments:_ --no-half --precision full --no-half-vae --xformers
_XFORMERS:_ 0.016rc425
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ FULL
_Batch Size_: 1

Result:

3.31 it/s raw | 3.04 it/s load
3.31 it/s avg @ BS1

**Comment by 78Alpha** [comment]
### TESLA P40

**Test 11**

_Command Line Arguments:_ --no-half --precision full --no-half-vae --xformers
_XFORMERS:_ 0.016rc425
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ FULL
_Batch Size_: 8

Result:

1.65 s/it raw | 1.85 s/it load
4.84 it/s avg @ BS8

**Comment by 78Alpha** [comment]
### TESLA P40

**Test 12**

_Command Line Arguments:_ --no-half --precision full --no-half-vae --xformers
_XFORMERS:_ 0.016rc425
_Torch:_ 1.13.1+cu117
_CuDNN:_ 8.8.0
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ FULL
_Batch Size_: 1

Result:

3.78 it/s raw | 3.51 it/s load
3.78 it/s avg @ BS1

**Comment by 78Alpha** [comment]
### TESLA P40

**Test 13**

_Command Line Arguments:_ --no-half --precision full --no-half-vae --xformers
_XFORMERS:_ 0.016rc425
_Torch:_ 1.13.1+cu117
_CuDNN:_ 8.8.0
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ FULL
_Batch Size_: 8

Result:

1.65 s/it raw | 1.82 s/it load
4.84 it/s avg @ BS8

**Comment by 78Alpha** [comment]
### TESLA P40

**Test 14**

_Command Line Arguments:_ --no-half --precision full --no-half-vae --xformers
_XFORMERS:_ 0.0.17+b89a493.d20230307
_Torch:_ 1.13.1+cu117
_CuDNN:_ 8.8.0
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ FULL
_Batch Size_: 1

Result:

3.74 it/s raw | 3.46 it/s load
3.74 it/s avg @ BS1

**Comment by 78Alpha** [comment]
### TESLA P40

**Test 15**

_Command Line Arguments:_ --no-half --precision full --no-half-vae --xformers
_XFORMERS:_ 0.0.17+b89a493.d20230307
_Torch:_ 1.13.1+cu117
_CuDNN:_ 8.8.0
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ FULL
_Batch Size_: 8

Result:

1.67 s/it raw | 1.84 s/it load
4.79 it/s avg @ BS8

**Comment by 78Alpha** [comment]
### RTX 3090

**Test 1**

_Command Line Arguments:_ N/A
_XFORMERS:_ False
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ Autocast
_Batch Size_: 1

Result:

12.91 it/s raw | 11.34 it/s load
12.91 it/s avg @ BS1

**Comment by 78Alpha** [comment]
### RTX 3090

**Test 2**

_Command Line Arguments:_ N/A
_XFORMERS:_ False
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ Autocast
_Batch Size_: 8

Result:

2.24 it/s raw | 1.88 it/s load
17.92 it/s avg @ BS8

**Comment by 78Alpha** [comment]
### RTX 3090

**Test 3**

_Command Line Arguments:_ --autolaunch --xformers
_XFORMERS:_ 0.0.16rc425
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ Autocast
_Batch Size_: 1

Result:

16.95 it/s raw | 14.20 it/s load
16.95 it/s avg @ BS1

**Comment by 78Alpha** [comment]
### RTX 3090

**Test 4**

_Command Line Arguments:_ --autolaunch --xformers
_XFORMERS:_ 0.0.16rc425
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ False
_Precision:_ Autocast
_Batch Size_: 8

Result:

3.10 it/s raw | 2.46 it/s load
24.8 it/s avg @ BS8

**Comment by 78Alpha** [comment]
### RTX 3090

**Test 5**

_Command Line Arguments:_ --autolaunch --xformers --opt-channelslast
_XFORMERS:_ 0.0.16rc425
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ True
_Precision:_ Autocast
_Batch Size_: 1

Result:

16.37 it/s raw | 13.39 it/s load
16.37 it/s avg @ BS1

**Comment by 78Alpha** [comment]
### RTX 3090

**Test 5**

_Command Line Arguments:_ --autolaunch --xformers --opt-channelslast
_XFORMERS:_ 0.0.16rc425
_Torch:_ 1.13.1+cu117
_CuDNN:_ Default
_Triton:_ False
_Opt-channelslast:_ True
_Precision:_ Autocast
_Batch Size_: 8

Result:

3.07 it/s raw | 2.37 it/s load
24.56 it/s avg @ BS8
